# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mariyant/Desktop/project/textadventure

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mariyant/Desktop/project/textadventure

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mariyant/Desktop/project/textadventure/CMakeFiles /home/mariyant/Desktop/project/textadventure/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mariyant/Desktop/project/textadventure/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named npcDataInterface

# Build rule for target.
npcDataInterface: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 npcDataInterface
.PHONY : npcDataInterface

# fast build rule for target.
npcDataInterface/fast:
	$(MAKE) -f lib/npcDataInterface/CMakeFiles/npcDataInterface.dir/build.make lib/npcDataInterface/CMakeFiles/npcDataInterface.dir/build
.PHONY : npcDataInterface/fast

#=============================================================================
# Target rules for targets named objDataInterface

# Build rule for target.
objDataInterface: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 objDataInterface
.PHONY : objDataInterface

# fast build rule for target.
objDataInterface/fast:
	$(MAKE) -f lib/objDataInterface/CMakeFiles/objDataInterface.dir/build.make lib/objDataInterface/CMakeFiles/objDataInterface.dir/build
.PHONY : objDataInterface/fast

#=============================================================================
# Target rules for targets named Character

# Build rule for target.
Character: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Character
.PHONY : Character

# fast build rule for target.
Character/fast:
	$(MAKE) -f lib/gameEngine/CMakeFiles/Character.dir/build.make lib/gameEngine/CMakeFiles/Character.dir/build
.PHONY : Character/fast

#=============================================================================
# Target rules for targets named Door

# Build rule for target.
Door: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Door
.PHONY : Door

# fast build rule for target.
Door/fast:
	$(MAKE) -f lib/gameEngine/CMakeFiles/Door.dir/build.make lib/gameEngine/CMakeFiles/Door.dir/build
.PHONY : Door/fast

#=============================================================================
# Target rules for targets named Monster

# Build rule for target.
Monster: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Monster
.PHONY : Monster

# fast build rule for target.
Monster/fast:
	$(MAKE) -f lib/gameEngine/CMakeFiles/Monster.dir/build.make lib/gameEngine/CMakeFiles/Monster.dir/build
.PHONY : Monster/fast

#=============================================================================
# Target rules for targets named NPC

# Build rule for target.
NPC: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NPC
.PHONY : NPC

# fast build rule for target.
NPC/fast:
	$(MAKE) -f lib/gameEngine/CMakeFiles/NPC.dir/build.make lib/gameEngine/CMakeFiles/NPC.dir/build
.PHONY : NPC/fast

#=============================================================================
# Target rules for targets named Object

# Build rule for target.
Object: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Object
.PHONY : Object

# fast build rule for target.
Object/fast:
	$(MAKE) -f lib/gameEngine/CMakeFiles/Object.dir/build.make lib/gameEngine/CMakeFiles/Object.dir/build
.PHONY : Object/fast

#=============================================================================
# Target rules for targets named Room

# Build rule for target.
Room: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Room
.PHONY : Room

# fast build rule for target.
Room/fast:
	$(MAKE) -f lib/gameEngine/CMakeFiles/Room.dir/build.make lib/gameEngine/CMakeFiles/Room.dir/build
.PHONY : Room/fast

#=============================================================================
# Target rules for targets named Widget

# Build rule for target.
Widget: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Widget
.PHONY : Widget

# fast build rule for target.
Widget/fast:
	$(MAKE) -f lib/gameEngine/CMakeFiles/Widget.dir/build.make lib/gameEngine/CMakeFiles/Widget.dir/build
.PHONY : Widget/fast

#=============================================================================
# Target rules for targets named World

# Build rule for target.
World: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 World
.PHONY : World

# fast build rule for target.
World/fast:
	$(MAKE) -f lib/gameEngine/CMakeFiles/World.dir/build.make lib/gameEngine/CMakeFiles/World.dir/build
.PHONY : World/fast

#=============================================================================
# Target rules for targets named Login

# Build rule for target.
Login: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Login
.PHONY : Login

# fast build rule for target.
Login/fast:
	$(MAKE) -f lib/userAccount/CMakeFiles/Login.dir/build.make lib/userAccount/CMakeFiles/Login.dir/build
.PHONY : Login/fast

#=============================================================================
# Target rules for targets named TCPClient

# Build rule for target.
TCPClient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TCPClient
.PHONY : TCPClient

# fast build rule for target.
TCPClient/fast:
	$(MAKE) -f lib/networkingInterface/CMakeFiles/TCPClient.dir/build.make lib/networkingInterface/CMakeFiles/TCPClient.dir/build
.PHONY : TCPClient/fast

#=============================================================================
# Target rules for targets named TCPDataflow

# Build rule for target.
TCPDataflow: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TCPDataflow
.PHONY : TCPDataflow

# fast build rule for target.
TCPDataflow/fast:
	$(MAKE) -f lib/networkingInterface/CMakeFiles/TCPDataflow.dir/build.make lib/networkingInterface/CMakeFiles/TCPDataflow.dir/build
.PHONY : TCPDataflow/fast

#=============================================================================
# Target rules for targets named TCPServer

# Build rule for target.
TCPServer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TCPServer
.PHONY : TCPServer

# fast build rule for target.
TCPServer/fast:
	$(MAKE) -f lib/networkingInterface/CMakeFiles/TCPServer.dir/build.make lib/networkingInterface/CMakeFiles/TCPServer.dir/build
.PHONY : TCPServer/fast

#=============================================================================
# Target rules for targets named Commands

# Build rule for target.
Commands: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Commands
.PHONY : Commands

# fast build rule for target.
Commands/fast:
	$(MAKE) -f lib/userInterface/CMakeFiles/Commands.dir/build.make lib/userInterface/CMakeFiles/Commands.dir/build
.PHONY : Commands/fast

#=============================================================================
# Target rules for targets named ObserverList

# Build rule for target.
ObserverList: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ObserverList
.PHONY : ObserverList

# fast build rule for target.
ObserverList/fast:
	$(MAKE) -f lib/userInterface/CMakeFiles/ObserverList.dir/build.make lib/userInterface/CMakeFiles/ObserverList.dir/build
.PHONY : ObserverList/fast

#=============================================================================
# Target rules for targets named UserInterface

# Build rule for target.
UserInterface: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 UserInterface
.PHONY : UserInterface

# fast build rule for target.
UserInterface/fast:
	$(MAKE) -f lib/userInterface/CMakeFiles/UserInterface.dir/build.make lib/userInterface/CMakeFiles/UserInterface.dir/build
.PHONY : UserInterface/fast

#=============================================================================
# Target rules for targets named alphaversion

# Build rule for target.
alphaversion: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 alphaversion
.PHONY : alphaversion

# fast build rule for target.
alphaversion/fast:
	$(MAKE) -f tools/mainProgram/CMakeFiles/alphaversion.dir/build.make tools/mainProgram/CMakeFiles/alphaversion.dir/build
.PHONY : alphaversion/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... npcDataInterface"
	@echo "... objDataInterface"
	@echo "... Character"
	@echo "... Door"
	@echo "... Monster"
	@echo "... NPC"
	@echo "... Object"
	@echo "... Room"
	@echo "... Widget"
	@echo "... World"
	@echo "... Login"
	@echo "... TCPClient"
	@echo "... TCPDataflow"
	@echo "... TCPServer"
	@echo "... Commands"
	@echo "... ObserverList"
	@echo "... UserInterface"
	@echo "... alphaversion"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

